# Generated by Django 5.1.4 on 2024-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='fio',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
    ]
